version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
    container_name: elasticsearch
    environment:
#      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
#      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"     #Set this for dev environment. For prod set vm.max_map_count=262144. See Elastic install docs.
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml   
    environment:
      - 'server.host: "localhost"'   #How to bind to IP?
    depends_on: 
      - elasticsearch
    ports:
      - 5601:5601
    networks:
      - frontend
      - backend
  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.0
    depends_on:
      - elasticsearch
    ports:
      - 3000:3000
    volumes:  
      - ./pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./conf.d/:/etc/logstash/conf.d/
    networks:
      - frontend
      - backend

volumes:
  esdata1:
    driver: local

networks:
  backend:
  frontend:

#Under Docker, Logstash logs go to standard output by default. 
#To change this behaviour, use any of the techniques above to replace the file at /usr/share/logstash/config/log4j2.properties